conf: bump to ruby 3.3.10 (#623)
# Re: #620

## Goal
Fix [Ruby version mismatch
failure](https://github.com/FoveaCentral/vaccinesignup/actions/runs/19482090517/job/55755777492)
in #620:

> /opt/hostedtoolcache/Ruby/3.3.10/x64/bin/bundle install --jobs 4
> Your Ruby version is 3.3.10, but your Gemfile specified 3.3.6
> Error: The process '/opt/hostedtoolcache/Ruby/3.3.10/x64/bin/bundle'
failed with exit code 18

## Approach
1. Replace `3.3.6` with `3.3.10`.
2. `bundle install`
3. Copy `test.yml` from #620.

Signed-off-by: Roderick Monje <rod@foveacentral.com>

---------

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>