build(deps): bump rails from 6.1.6.1 to 7.1.3.2 (#383)
* build(deps): bump rails from 6.1.6.1 to 7.1.3.2

Bumps [rails](https://github.com/rails/rails) from 6.1.6.1 to 7.1.3.2.
- [Release notes](https://github.com/rails/rails/releases)
- [Commits](https://github.com/rails/rails/compare/v6.1.6.1...v7.1.3.2)

---
updated-dependencies:
- dependency-name: rails
  dependency-type: direct:production
  update-type: version-update:semver-major
...

Signed-off-by: dependabot[bot] <support@github.com>

* fix: LoadError

LoadError: cannot load such file -- sprockets/railtie (LoadError)
<internal:/opt/hostedtoolcache/Ruby/3.2.3/x64/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'

* fix: RuntimeError

/home/runner/work/vaccinesignup/vaccinesignup/vendor/bundle/ruby/3.2.0/gems/spring-4.2.0/lib/spring/application.rb:105:in `block in preload': Spring reloads, and therefore needs the application to have reloading enabled.

* Revert "fix: RuntimeError"

This reverts commit 0db5a9ab6909f3614b84daefce2918955b0c4811.

* fix?: RuntimeError

/home/runner/work/vaccinesignup/vaccinesignup/vendor/bundle/ruby/3.2.0/gems/spring-4.2.0/lib/spring/application.rb:105:in `block in preload': Spring reloads, and therefore needs the application to have reloading enabled.
Please, set config.cache_classes to false in config/environments/test.rb.
 (RuntimeError)
	from /home/runner/work/vaccinesignup/vaccinesignup/vendor/bundle/ruby/3.2.0/gems/railties-7.1.3.2/lib/rails/initializable.rb:32:in `instance_exec'
	from /home/runner/work/vaccinesignup/vaccinesignup/vendor/bundle/ruby/3.2.0/gems/railties-7.1.3.2/lib/rails/initializable.rb:32:in `run'

* fix?: RuntimeError

/Users/oblomov/.asdf/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/spring-4.2.1/lib/spring/application.rb:105:in `block in preload': Spring reloads, and therefore needs the application to have reloading enabled.
Please, set config.cache_classes to false in config/environments/test.rb.

* fix: DEPRECATION WARNING

Support for `config.active_support.cache_format_version = 6.1` has been deprecated and will be removed in Rails 7.2.

* Revert "fix?: RuntimeError"

This reverts commit f349261845000f6f31ab8a84bf948f7d6197f82c.

* fix: deprecation warning

Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v2, aktions/codeclimate-test-reporter@v1, coverallsapp/github-action@master. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

* fix?: RuntimeError

/home/runner/work/vaccinesignup/vaccinesignup/vendor/bundle/ruby/3.2.0/gems/spring-4.2.1/lib/spring/application.rb:105:in `block in preload': Spring reloads, and therefore needs the application to have reloading enabled.
Please, set config.cache_classes to false in config/environments/test.rb.
 (RuntimeError)
	from /home/runner/work/vaccinesignup/vaccinesignup/vendor/bundle/ruby/3.2.0/gems/railties-7.1.3.2/lib/rails/initializable.rb:32:in `instance_exec'
	from /home/runner/work/vaccinesignup/vaccinesignup/vendor/bundle/ruby/3.2.0/gems/railties-7.1.3.2/lib/rails/initializable.rb:32:in `run'

---------

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Co-authored-by: Roderick Monje <rod@foveacentral.com>