fix: LoadError
LoadError: cannot load such file -- sprockets/railtie (LoadError)
<internal:/opt/hostedtoolcache/Ruby/3.2.3/x64/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'